import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import './assets/css/freelancer.min.css';
import './assets/css/bootstrap.css';
import './assets/css/bootstrap-grid.css';
import './assets/font-awesome/css/font-awesome.css';
import './assets/scss/_footer.scss';
import './assets/scss/_bootstrap-overrides.scss';
import './assets/scss/_contact.scss';
import './assets/scss/_global.scss';
import './assets/scss/_masthead.scss';
import './assets/scss/_mixins.scss';
import './assets/scss/_navbar.scss';
import './assets/scss/_portfolio.scss';
import './assets/scss/_variables.scss';
import './assets/scss/freelancer.scss';
import registerServiceWorker from './registerServiceWorker';

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
